### ISSUE TITLE
Question about importing _colors.scss

### ISSUE THREAD

**Issue by PooperPig** [maxime1992/pizza-sync#34]
Terrific sample project, by the way.

According to https://material.angular.io/guide/theming

> The theme file should not be imported into other SCSS files. This will cause duplicate styles to be written into your CSS output. If you want to consume the theme definition object (e.g., $candy-app-theme) in other SCSS files, then the definition of the theme object should be broken into its own file, separate from the inclusion of the mat-core and angular-material-theme mixins.

I'm (very) new to scss and Angular Material, so I may be miss-interpreting this, but where you 
`@import '../../styles/shared/_colors';`

eg in _features.component.scss_
isn't this doing just what the above tells us not to do, as mat-core is included in _colors.scss?

**Comment by maxime1992** [comment]
Thank you @PooperPig !

Indeed, it doesn't seem to be a good idea. 

I feel like I'm kinda lost with theming in Material. (take a look to [one](https://twitter.com/sizerOne/status/862279767537700865) of my tweets ...)

If you see other problems, feel free to create other issues or even make a PR if you have time :smile: 

About this one, I'll try to fix that in the next few weeks. When it's done I'll ping this thread to let you know :+1: 

Also, if you like pizza-sync, you might want to take a look into [angular-ngrx-starter](https://github.com/maxime1992/angular-ngrx-starter). Pizza-Sync is built upon it, and everything that is made on the starter is reported to pizza-sync.

**Comment by PooperPig** [comment]
Here's what I have: Literally worked it out today - so will be interested in any comments:
in styles.scss
```
@import '~@angular/material/theming';
@include mat-core();
@import './app/shared/styles/themes/ambrose-theme';
@include angular-material-theme($ambrose-theme);

```
in _ambrose_theme.scss
```

@import '~@angular/material/theming';
// @include mat-core(); <- this moved to main style to avoid being included in every component

$ambrose-primary: mat-palette($mat-light-green);
$ambrose-accent:  mat-palette($mat-grey, A200, A100, A400);
$ambrose-warn: mat-palette($mat-red);

$ambrose-theme: mat-light-theme($ambrose-primary, $ambrose-accent, $ambrose-warn);

@include angular-material-theme($ambrose-theme);

@mixin ambrose-theme($theme) {
  // Extract whichever individual palettes you need from the theme.
  $primary: map-get($theme, primary);
  $accent: map-get($theme, accent);
}

```
then in any component.scss
```
@import '../../shared/styles/shared';

// Row styling
.odd {
  background-color: mat-color($ambrose-primary, 400);
  color: mat-color($ambrose-primary, 100);
}
.even {
 background-color: mat-color($ambrose-primary);
  color: mat-color($ambrose-primary, 200);
}
.heading {
 background-color: mat-color($ambrose-accent, 800);
 color:  mat-color($ambrose-primary, 100);font-weight: bold;
}

```
I *believe* that this avoids copying mat_core multiple times (but I haven't had a chance to investigate yet)

Cheers

Max

**Comment by maxime1992** [comment]
> I believe that this avoids copying mat_core multiple times (but I haven't had a chance to investigate yet)

Did you have any chance to investigate? :)
Should we close this issue? Let it open? Make a fix?

**Comment by maxime1992** [comment]
I'm closing this for now, if you make a PR or feel like this discussion is not over, feel free to reopen :smile:
