### ISSUE TITLE
Logo Design Proposal for Pizza-sync

### ISSUE THREAD

**Issue by happyksu** [maxime1992/pizza-sync#63]
Hi, my name is Ksenia. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo design for your project. If it's something you're interested in, please, let me know!

Best regards,
Ksenia

**Comment by maxime1992** [comment]
Hi @happyksu ! That's a brilliant idea, thanks for opening this issue :smile: 

I have been putting this side project on pause for quite a while but spent few hours this week end to update things around! 

If you do have multiple ideas, you could raise one MR per logo including the final PNG + the source (PSD? AI?). I'll ask around what people think and some time later we can settle on the favourite one :smile_cat: 

Let me know if you have any questions.

**Comment by happyksu** [comment]
Happy to hear that! Hope this project will succeed 😄 

So you are interested in logo, right? Did I understand correctly? You ask me to provide you with different types of files like psd, ai and others when it will be ready? It is not a problem. 

Can you tell me what do you mean saying "raise one MR per logo"? (I'm sorry if it is stupid question; English is not my native language)

Well, I already have few ideas and can share with you sketches tomorrow 😄 Do you have any special requirements for the logo? Any symbols or text that should be included? And how do you plan to use the logo? On your web site and etc?

**Comment by maxime1992** [comment]
> So you are interested in logo, right?

Yes, definitely!

> You ask me to provide you with different types of files like psd, ai and others when it will be ready?

Yes, that'll be better in case we want to make some modification later.
I'd like the source file (PSD, AI, ...) to be versioned just like we do with the code.

> Can you tell me what do you mean saying "raise one MR per logo"? (I'm sorry if it is stupid question; English is not my native language)

Nothing stupid, feel free to ask as many questions as needed. (and English is not my native language so I know the struggle, no worries!)
MR stands for "Merge Request". I don't know how much you know about Git and Github but if you need any help on how to do that let me know and I'll guide you through.

> Well, I already have few ideas and can share with you sketches tomorrow

Brilliant! :raised_hands: 

> Do you have any special requirements for the logo? Any symbols or text that should be included?
Not much, feel free to try different things.
One thing though, I'd like the logo to be visible enough when it is display as a very small one on a browser tab. Currently it is:
![image](https://user-images.githubusercontent.com/4950209/43733124-82c7ab3a-99ab-11e8-97bf-759a42e3ac1d.png)

> And how do you plan to use the logo? On your web site and etc?

The logo will be displayed:
- On the README [here](https://github.com/maxime1992/pizza-sync)
- On the top nav bar of the web app
- On the tab 

Second thoughts about the MR:
Maybe don't bother raising a merge request for now.

Create one comment in this issue, per logo. Just name them with a number (1, 2, 3...) so we can reference them when we want to talk about one of them. Then when we pick one, we should have a merge request before merging it :)

**Comment by happyksu** [comment]
Thank you for understanding! 😄 It is second project I will work for. 
Tomorrow will share with you my ideas!

**Comment by happyksu** [comment]
Hi!
I prepared for you some ideas. If you will give me link to your website or its color scheme I will work better on logo colors. Please, let me know what do you think?
![pizza-sync logo](https://user-images.githubusercontent.com/41577905/43772751-d1a42a26-9a4b-11e8-98f8-19a194aa6721.jpg)

**Comment by maxime1992** [comment]
Hey!

> If you will give me link to your website or its color scheme I will work better on logo colors

You can build it locally but if you don't want to deal with that, I've taken one screenshot that you should be able to play with

![image](https://user-images.githubusercontent.com/4950209/43792690-6282490e-9a71-11e8-88be-121e30af2001.png)

Nice for the logos! :smile: 

My favourites are: 5, 8, 1!

As the website is built using Material, if the logo might have a "Material design" look I think it'd be really cool.

**Comment by johnnyraper** [comment]
Hi @maxime1992 and @happyksu,

First of all this looks like a great application and design (I am in favour of anything involving pizza), nice job!

I am not a designer, but thought I would contribute some ideas of my own for a logo design and see if they can be mocked up. 

I really like the idea of showing toppings on a slice of pizza. As this application uses Angular Material, would it be possible to show the Angular logo as a topping for the pizza? Or maybe multiple Angular logos if there is space. I realise there's only a small amount of space to work in, so not sure if this would look to cluttered. I am happy to provide a mockup of what I mean, if this is unclear...

Alternatively, perhaps another logo idea could be two rows of triangles that tessellate together (to play on the idea of "syncing"). What do you guys think? 

Look forward to hearing your thoughts!

Best,
Johnny

**Comment by maxime1992** [comment]
I love the idea of having an Angular logo of topping! Not sure it'll be good, but definitely worth a try :smile:  !

Also, do you think @happyksu that you could try to create a new proposal based on what you've done here: https://github.com/maxime1992/pizza-sync/issues/63#issuecomment-411343704 but with the pizza feeling a bit more... material design? You might found some inspiration here for ex https://www.google.co.uk/search?q=material+design+pizza&tbm=isch

**Comment by happyksu** [comment]
Hi @johnnyraper ! It is nice idea but if this application will be used for public and not for group of people that know about Angular it will be strange. Will this app be available to ordinary people like me? 😄 

@maxime1992 Can you be more specific? 😄  Do you want more details on pizza? Most of things [here](https://www.google.co.uk/search?q=material+design+pizza&tbm=isch#imgrc=_) is not material design. I thought when you said "material design" you meant simple and clear.

Topping like this?
![1](https://user-images.githubusercontent.com/41577905/43862499-8f9e35aa-9b62-11e8-866e-cfcf4d2dcf63.jpg)

**Comment by maxime1992** [comment]
That's awesome :heart_eyes: ! I really like the second one with one slice and one Angular logo!

Not 100% sure about the font though :thinking: Could you try to make a few different? I mean the same but just trying out with different fonts? 

> It is nice idea but if this application will be used for public and not for group of people that know about Angular it will be strange. Will this app be available to ordinary people like me? smile

If you go through the readme you'll see that this app is mainly for developers! The main purpose is to have an Angular app to learn things around ngrx but with an app bigger than an hello world or a todo list. (and I've also been using it at my previous office a lot to order in group with my former co-workers :smile_cat:).

Nice job so far @happyksu :)!

**Comment by johnnyraper** [comment]
😃 I like your work @happyksu! I really like the first one, the "arc" design is my favourite. Not sure if like the text alignment, but the arc shape is awesome.

I think it's quite ironic that the "A" shapes on the slice also work as the missing "A" for "Pizza" in the logo (even though your intent already was to use the slice to form the A shape, I feel this works well too). 

Another idea I had would be to use two half-circle arrows to form a circle, to represent syncing. This could also resemble the circumference of a pizza... maybe something like: https://www.iconfinder.com/icons/183664/arrows_reload_sync_update_icon

**Comment by happyksu** [comment]
@maxime1992 thank you!
@maxime1992 and @johnnyraper what kind of fonts do you like? And I made for you another logo as well.
Hope you like my work and will choose one logo that you like for project so I can make for you final version 😄 
![pizza fonts](https://user-images.githubusercontent.com/41577905/43893959-5843eb8c-9bd9-11e8-8e8c-adfd54fc2e8a.jpg)

**Comment by maxime1992** [comment]
Hey,

I really like the idea of this one:

![image](https://user-images.githubusercontent.com/4950209/43922581-153de200-9c17-11e8-9014-1446b37051cf.png)


That said, the logo will be huge and it'll be hard to see it on a smaller version.

So I'll go for my second favourite, in the font section, starting from the top: 2nd on the right
![image](https://user-images.githubusercontent.com/4950209/43922681-5793d010-9c17-11e8-8b86-212823d37c09.png)

Can you please raise a merge request including:
- the source (PSD?)
- the final image as a png

And another one that will be used for the favicon with the same things (source + png).

You can create a new folder at the root of the project and do something like that:
```
|-- frontend/
|-- backend/
|-- logo/
    |--logo/
      |--logo.psd
      |--logo.png
    |--favicon/
      |--favicon.psd
      |--favicon.png
```

If you're not familiar with merge request just let me know and I'll try to help you :)

Thanks!

**Comment by happyksu** [comment]
I also think that it will be too big for your website.

Great! I like that font.

Sure, I will prepare everything tomorrow and write you when everything will be uploaded :)

**Comment by happyksu** [comment]
Hi! I uploaded all the required files and created a pull-request. Please merge it if everything is Ok 😄

**Comment by happyksu** [comment]
Hi!
I just wanted to ask is everything ok with my merge request?

**Comment by maxime1992** [comment]
Hi, I replied directly on the merge request :smile_cat:
